version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
      
    working_directory: /go/src/github.com/alvelcom/berny
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make build
      - run: make test
